### ISSUE TITLE
Refresco automático de tabla de archivos

### ISSUE THREAD

**Issue by jesubiag** [jesubiag/VaadinTest01#18]
Luego de cargarse exitósamente un archivo el método que sea, se debe permanecer en la misma vista y refrescar automáticamente la tabla para mostrar el nuevo archivo cargado.
Actualmente esto no funciona, y la redirección se hace a otra vista. El refresco se hace cuando se navega nuevamente a la materia solamente.
Si no se consigue mediante un Listener el comportamiento deseado, probablemente haya que reprogramar la tabla. Actualmente se usa un custom component con una tabla, en vez de la tabla Table asociada a un JPAContainer provista por el framework, que tiene funcionalidades más completas. La razón de esto era para incluir un elemento Link en la tabla, cosa que no sea había conseguido usando JPAContainer.
Se propone utilizar una tabla con un JPAContainer asociado. Y de no encontrarse una mejor formar de introducir el elemento Link en la tabla, quizas la única opción sea modificar la entidad para que el atributo link pase de ser un String a un Link.

**Comment by mcruz342** [comment]
Solucionado navegando a la vista de la materia y seleccionando la tab en la que se estaba, de esta manera se refresca la tabla.
